# ================================================================================================================================================
#       
# Define your configuration options here
# 
# Author: Guilherme Santos
# Last edited: 02/March/2024 
# ========================================================================================================================================================

dataset_path: data/CellCycle_single.arff

GMNBwGA:
  activate: false # Activate the GMNBwGA algorithm, true or false
  population_size: 10 
  num_generations: 100
  crossover_rate: 0.9
  mutation_rate: 0.1
  tournament_winner_rate: 0.75

NNwGA: 
  activate: true # Activate the NNwGA algorithm, true or false
  population_size: 800
  num_generations: 500
  crossover_rate: 0.9
  mutation_rate: 0.1
  tournament_winner_rate: 0.75
  
  GMNB_generations: 0 # Number of generations to train the GMNB model, the data will be used to train the NN model
  train_epochs: 1000 # Number of epochs to train the NN model
  
  save_model: true
  save_path: ./model_CellCycle.keras # Do not forget to put .keras extension 

  load_model: false # Use this option if you want to load a pre-trained model
  load_path: ./model_CellCycle.keras # Use this option if you want to load a pre-trained model




        
